name: test-full-workflow
run-name: Testing full Packit action workflow
on: 
  workflow_dispatch:
    inputs:
      packit_version:
        description: 'The Packit version to use for testing'
        required: true
        type: string
        default: 0.0.5
      pr:
        description: 'The PR on pack-it/core to test'
        required: true
        type: number

jobs:
  define-matrix-linux:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.detect-changes.outputs.packages }}
    steps:
      - uses: actions/checkout@v6
        with:
          repository: pack-it/core
          ref: refs/pull/${{ inputs.pr }}/head
      - uses: pack-it/actions/setup-packit@main
        name: "Setup Packit"
        with:
          version: ${{ inputs.packit_version }}
          repository-url: ${{ github.workspace }}
          repository-provider: fs
      - uses: pack-it/actions/detect-changed-packages@main
        name: "Detect changed packages"
        id: detect-changes
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr: ${{ inputs.pr }}
          repo-owner: pack-it
          repo-name: core
          filter-unsupported: true
          output-json: true
  test-linux:
    runs-on: ubuntu-latest
    needs: define-matrix-linux
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJSON(needs.define-matrix-linux.outputs.packages) }}

    steps:
      - uses: actions/checkout@v6
        with:
          repository: pack-it/core
          ref: refs/pull/${{ inputs.pr }}/head
      - uses: pack-it/actions/setup-packit@main
        name: "Setup Packit"
        with:
          version: ${{ inputs.packit_version }}
          repository-url: ${{ github.workspace }}
          repository-provider: fs
      - name: Install package
        run: pit install ${{ matrix.package }} --build-all --keep-build --verbose --skip-symlinking --skip-active --execute-build-test
  

  define-matrix-macos:
    runs-on: macos-latest
    outputs:
      packages: ${{ steps.detect-changes.outputs.packages }}
    steps:
      - uses: actions/checkout@v6
        with:
          repository: pack-it/core
          ref: refs/pull/${{ inputs.pr }}/head
      - uses: pack-it/actions/setup-packit@main
        name: "Setup Packit"
        with:
          version: ${{ inputs.packit_version }}
          repository-url: ${{ github.workspace }}
          repository-provider: fs
      - uses: pack-it/actions/detect-changed-packages@main
        name: "Detect changed packages"
        id: detect-changes
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr: ${{ inputs.pr }}
          repo-owner: pack-it
          repo-name: core
          filter-unsupported: true
          output-json: true
  test-macos:
    runs-on: macos-latest
    needs: define-matrix-macos
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJSON(needs.define-matrix-macos.outputs.packages) }}

    steps:
      - uses: actions/checkout@v6
        with:
          repository: pack-it/core
          ref: refs/pull/${{ inputs.pr }}/head
      - uses: pack-it/actions/setup-packit@main
        name: "Setup Packit"
        with:
          version: ${{ inputs.packit_version }}
          repository-url: ${{ github.workspace }}
          repository-provider: fs
      - name: Install package
        run: pit install ${{ matrix.package }} --build-all --keep-build --verbose --skip-symlinking --skip-active --execute-build-test
  
  
  define-matrix-windows:
    runs-on: windows-latest
    outputs:
      packages: ${{ steps.detect-changes.outputs.packages }}
    steps:
      - uses: actions/checkout@v6
        with:
          repository: pack-it/core
          ref: refs/pull/${{ inputs.pr }}/head
      - uses: pack-it/actions/setup-packit@main
        name: "Setup Packit"
        with:
          version: ${{ inputs.packit_version }}
          repository-url: ${{ github.workspace }}
          repository-provider: fs
      - uses: pack-it/actions/detect-changed-packages@main
        name: "Detect changed packages"
        id: detect-changes
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr: ${{ inputs.pr }}
          repo-owner: pack-it
          repo-name: core
          filter-unsupported: true
          output-json: true
  test-windows:
    runs-on: windows-latest
    needs: define-matrix-windows
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJSON(needs.define-matrix-windows.outputs.packages) }}

    steps:
      - uses: actions/checkout@v6
        with:
          repository: pack-it/core
          ref: refs/pull/${{ inputs.pr }}/head
      - uses: pack-it/actions/setup-packit@main
        name: "Setup Packit"
        with:
          version: ${{ inputs.packit_version }}
          repository-url: ${{ github.workspace }}
          repository-provider: fs
      - name: Install package
        run: pit install ${{ matrix.package }} --build-all --keep-build --verbose --skip-symlinking --skip-active --execute-build-test
