name: test-full-workflow
run-name: Testing full Packit action workflow
on: [push]

env:
  PR: 85

jobs:
  define-matrix-linux:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.detect-changes.outputs.packages }}
    steps:
      - uses: actions/checkout@v6
        with:
          repository: pack-it/core
          ref: refs/pull/${{ env.PR }}/head
      - uses: pack-it/actions/setup-packit@main
        name: "Setup Packit"
        with:
          version: 0.0.4
          repository-url: ${{ github.workspace }}
          repository-provider: fs
      - uses: pack-it/actions/detect-changed-packages@main
        name: "Detect changed packages"
        id: detect-changes
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr: ${{ env.PR }}
          repo-owner: pack-it
          repo-name: core
          filter-unsupported: true
          output-json: true
  test-linux:
    runs-on: ubuntu-latest
    needs: define-matrix-linux
    strategy:
      matrix:
        package: ${{ fromJSON(needs.define-matrix-linux.outputs.packages) }}

    steps:
      - uses: actions/checkout@v6
        with:
          repository: pack-it/core
          ref: refs/pull/${{ env.PR }}/head
      - uses: pack-it/actions/setup-packit@main
        name: "Setup Packit"
        with:
          version: 0.0.4
          repository-url: ${{ github.workspace }}
          repository-provider: fs
      - name: Install package
        run: pit install ${{ matrix.package }} --build-all --keep-build --verbose --skip-symlinking --skip-active
  

  define-matrix-macos:
    runs-on: macos-latest
    outputs:
      packages: ${{ steps.detect-changes.outputs.packages }}
    steps:
      - uses: actions/checkout@v6
        with:
          repository: pack-it/core
          ref: refs/pull/${{ env.PR }}/head
      - uses: pack-it/actions/setup-packit@main
        name: "Setup Packit"
        with:
          version: 0.0.4
          repository-url: ${{ github.workspace }}
          repository-provider: fs
      - uses: pack-it/actions/detect-changed-packages@main
        name: "Detect changed packages"
        id: detect-changes
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr: ${{ env.PR }}
          repo-owner: pack-it
          repo-name: core
          filter-unsupported: true
          output-json: true
  test-macos:
    runs-on: macos-latest
    needs: define-matrix-macos
    strategy:
      matrix:
        package: ${{ fromJSON(needs.define-matrix-macos.outputs.packages) }}

    steps:
      - uses: actions/checkout@v6
        with:
          repository: pack-it/core
          ref: refs/pull/${{ env.PR }}/head
      - uses: pack-it/actions/setup-packit@main
        name: "Setup Packit"
        with:
          version: 0.0.4
          repository-url: ${{ github.workspace }}
          repository-provider: fs
      - name: Install package
        run: pit install ${{ matrix.package }} --build-all --keep-build --verbose --skip-symlinking --skip-active
  
  
  define-matrix-windows:
    runs-on: windows-latest
    outputs:
      packages: ${{ steps.detect-changes.outputs.packages }}
    steps:
      - uses: actions/checkout@v6
        with:
          repository: pack-it/core
          ref: refs/pull/${{ env.PR }}/head
      - uses: pack-it/actions/setup-packit@main
        name: "Setup Packit"
        with:
          version: 0.0.4
          repository-url: ${{ github.workspace }}
          repository-provider: fs
      - uses: pack-it/actions/detect-changed-packages@main
        name: "Detect changed packages"
        id: detect-changes
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr: ${{ env.PR }}
          repo-owner: pack-it
          repo-name: core
          filter-unsupported: true
          output-json: true
  test-windows:
    runs-on: windows-latest
    needs: define-matrix-windows
    strategy:
      matrix:
        package: ${{ fromJSON(needs.define-matrix-windows.outputs.packages) }}

    steps:
      - uses: actions/checkout@v6
        with:
          repository: pack-it/core
          ref: refs/pull/${{ env.PR }}/head
      - uses: pack-it/actions/setup-packit@main
        name: "Setup Packit"
        with:
          version: 0.0.4
          repository-url: ${{ github.workspace }}
          repository-provider: fs
      - name: Install package
        run: pit install ${{ matrix.package }} --build-all --keep-build --verbose --skip-symlinking --skip-active
